name: Docs

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:

  build_docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          pip install sphinx==6.2.1 myst-parser sphinx-autodoc-typehints nbsphinx sphinx-gallery sphinx-rtd-theme sphinx-autodoc-annotation

      - uses: actions/checkout@v2

      - name: Install Package
        run: |
         pip install .

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Setup Envvars
        run: |
            if [[ $GITHUB_REF = "refs/tags/"* ]] ; then echo "PASTE3_VERSION=${GITHUB_REF/refs\/tags\//}" ; else echo "PASTE3_VERSION=" ; fi >> $GITHUB_ENV

      - name: Build docs
        run: |
          # Unless we add a .nojekyll to the base of the deployment folder, the underscores in foldernames
          # like _static/ etc. pose problems on GH Pages.
          cd docs && sphinx-apidoc -f -o src ../src/paste3 -H Modules && make html && touch build/html/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          branch: gh-pages
